# 配置数据库连接信息
spring:
  application:
    name: tlias-web-management
  #数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  servlet:
    multipart:
      # 单个文件上传的最大大小
      max-file-size: 10MB
      # 一个请求的最大大小(包括所有文件和表单数据)(因为是可以上传多个文件的)
      max-request-size: 100MB

#Mybatis的相关配置
mybatis:
  configuration:
    # 表示输出的sql语句打印到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 是否开启驼峰命名转换
    map-underscore-to-camel-case: true

# 设置事务的日志级别为debug
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

